version: '3.7'
services:
  mysql:
    image: mysql
    ports:
    - "3306:3306"
    - "33060:33060"
    environment: 
      MYSQL_ROOT_PASSWORD: root123456
    restart: unless-stopped
  redis:
    image: redis
    ports:
    - "6379:6379"
    restart: unless-stopped
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123456
    ports:
    - "27017:27017"
    - "27018:27018"
    - "27019:27019"
    - "28017:28017"
    restart: unless-stopped
  nats:
    image: nats
    ports:
    - "4222:4222"
    - "8222:8222"
    - "6222:6222"
    restart: unless-stopped
  postgres:  
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root123456
    restart: unless-stopped
  influxdb:
    image: influxdb
    ports:
    - "8086:8086"
    - "2003:2003"
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_ADMIN_USER: root
      INFLUXDB_ADMIN_PASSWORD: root123456
    restart: unless-stopped
  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
    - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123456
    command: server /data
    volumes:
    - ~/minio:/data    