version: '3.7'
services:
  mysql:
    image: mysql
    ports:
    - "3306:3306"
    - "33060:33060"
    volumes:
    - ~/data/mysql:/var/lib/mysql  
    environment: 
      MYSQL_ROOT_PASSWORD: root123456
    restart: unless-stopped
  mysql57:
    image: mysql:5.7
    ports:
    - "3307:3306"
    - "33070:33060"
    volumes:
    - ~/data/mysql57:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
    restart: unless-stopped
  redis:
    image: redis
    ports:
    - "6379:6379"
    restart: unless-stopped
    volumes:
    - ~/data/redis:/data        
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123456
    ports:
    - "27017:27017"
    - "27018:27018"
    - "27019:27019"
    - "28017:28017"
    restart: unless-stopped
    volumes:
    - ~/data/mongo:/data/db       
  nats:
    image: nats
    ports:
    - "4222:4222"
    - "8222:8222"
    - "6222:6222"
    restart: unless-stopped
  postgres:  
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root123456
    restart: unless-stopped
    volumes:
    - ~/data/postgresql:/var/lib/postgresql/data        
  influxdb:
    image: influxdb
    ports:
    - "8086:8086"
    - "2003:2003"
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_ADMIN_USER: root
      INFLUXDB_ADMIN_PASSWORD: root123456
    restart: unless-stopped
    volumes:
    - ~/data/influxdb:/var/lib/influxdb        
  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
    - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123456
    command: server /data
    volumes:
    - ~/data/minio:/data
  gitea:
    image: gitea/gitea
    restart: unless-stopped
    ports: 
    - "10022:22"
    - "10080:3000"
    volumes:
    - ~/data/gitea:/data
